[package]
name = "tiger"
version = "0.1.0"
authors = ["Kevin Oberlies <favilo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.1.0"
clap = "2.33.0"
log = "0.4.8"
simple_logger = "1.5.0"
